safe: false
timezone: America/Los_Angelos
encoding: utf-8
exclude: 
- sass
- README.md
- LICENSE
- config.rb

include:
- css

permalink: /blog/:title
pygments: true
paginate: 10
paginate_path: "blog/:num"
