url: "https://bryce.fisher-fleig.org"
rss_url: "http://bryce.fisher-fleig.org"
name: "Bryce Fisher-Fleig"
description: "Full Stack Forays into Web Development"

gems: [jekyll-paginate]

safe: false
timezone: America/Los_Angelos
encoding: utf-8
exclude:
- README.md
- config.rb
- delete-old-buckets.sh
- publish.sh
- list-categories.sh
- awscli
- .gitignore
- .travis.yml
- .jekyll-metadata

include:
- css
- favicon.ico
- .well-known

permalink: /blog/:title/index.html
relative_permalinks: false
paginate: 10
paginate_path: /blog/:num
markdown: kramdown

sass:
    sass_dir: css
