url: "https://bryce.fisher-fleig.org"
rss_url: "http://bryce.fisher-fleig.org"
name: "Bryce Fisher-Fleig"
description: "Full Stack Forays into Web Development"

safe: false
timezone: America/Los_Angelos
encoding: utf-8
exclude: 
- sass
- README.md
- LICENSE
- config.rb
- publish.sh

include:
- css
- favicon.ico

permalink: /blog/:title
relative_permalinks: false
pygments: true
paginate: 10
paginate_path: /blog/:num
markdown: kramdown
